version: '3.3'

services:
  backend_server:
    build: ./backend
    command: uvicorn src.app:app --host 0.0.0.0 --port 8000 --reload
    container_name: application_server
    environment:
      PROJECT_NAME: $PROJECT_NAME
  
  reverse_proxy:
    image: nginx:1.21.6
    container_name: nginx_proxy
    volumes:
      - ./frontend:/var/www/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/logs:/var/log/nginx
    ports:
      - 80:80
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    depends_on:
      - backend_server
    